Implement copy, cut and paste
webzard-io/sunmao-ui pull request #155
Opened 2021-12-07 05:36 UTC by tanbowensg

#103

2021-12-07 14:31 UTC, Yuyz0112 commented
@Sczlog PTAL

2021-12-08 10:16 UTC, Sczlog requested changes
cut operation can be reused, others LGTM.

2021-12-08 10:16 UTC, Sczlog commented on packages/editor/src/operations/leaf/component/cutComponentLeafOperation.ts
> +export class CutComponentLeafOperation extends BaseLeafOperation<CutComponentLeafOperationContext> {
we can reuse deleteCompoenentLeafOperation here.

2021-12-09 07:19 UTC, Sczlog approved these changes
LGTM

2021-12-10 08:01 UTC, Yuyz0112 commented
@tanbowensg please resolve the conflicts.

2021-12-13 10:26 UTC, merged