drag component into view to create component
webzard-io/sunmao-ui pull request #165
Opened 2021-12-14 02:29 UTC by tanbowensg

1. can drag component to component view to create component, but cannot drag to specific slot yet
#110

2021-12-15 14:10 UTC, Yuyz0112 requested changes

2021-12-16 08:22 UTC, tanbowensg commented
ping @Yuyz0112

2021-12-19 14:50 UTC, Yuyz0112 commented
LGTM. Can be merged after resolving the conflicts.

2021-12-20 02:57 UTC, tanbowensg commented
ok. @Yuyz0112

2021-12-20 03:30 UTC, Yuyz0112 approved these changes

2021-12-20 03:31 UTC, merged