Move addModuleId to Editor
webzard-io/sunmao-ui pull request #215
Opened 2022-01-18 09:39 UTC by tanbowensg

Move addModuleId to Editor. ApplicationSchema generated by editor will have `{{$moduleId__}}` in default and modules must have `{{$moduleId__}}` to be registered in registry.

2022-01-18 09:42 UTC, Yuyz0112 requested changes

2022-01-18 09:42 UTC, Yuyz0112 commented on packages/editor/src/utils/addModuleId.ts
> +export function addModuleId(module: Module): Module {
need some unit tests for thew following functions

2022-01-20 06:31 UTC, tanbowensg commented
ping @Yuyz0112

2022-01-20 16:25 UTC, Yuyz0112 approved these changes

2022-01-20 16:25 UTC, merged