feat(utilMethod): add spec to utilMethod
webzard-io/sunmao-ui pull request #422
Opened 2022-05-30 05:08 UTC by MrWindlike

BREAKING CHANGE:
use `type` to replace `name` when calling the method

ISSUES CLOSED: #248

2022-05-30 09:15 UTC, tanbowensg approved these changes

2022-05-30 09:15 UTC, tanbowensg commented on packages/core/src/utilMethod.ts
> +  king: 'UtilMethod';
king -> kind

2022-05-30 09:17 UTC, tanbowensg requested changes
Why do we need to use `type` to replace `name` when calling the method?

2022-05-30 10:45 UTC, MrWindlike commented
> Why do we need to use type to replace name when calling the method?

The different libs may have the same names of util methods.

2022-05-31 03:27 UTC, tanbowensg approved these changes

2022-05-31 03:28 UTC, merged