fix(runtime): nextjs localstorage is not defined
webzard-io/sunmao-ui pull request #677
Opened 2023-01-14 02:17 UTC by cyberbear181

add utils/isSSR

2023-01-14 02:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/smartxworks/sunmao-ui?pullRequest=677) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/smartxworks/sunmao-ui?pullRequest=677) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/smartxworks/sunmao-ui?pullRequest=677) it.</sub>

2023-01-14 04:50 UTC, cyberbear181 commented
<img width="967" alt="image" src="https://user-images.githubusercontent.com/120086676/212454494-618c9c38-48ef-4b53-99e5-939eae4f6643.png">

2023-01-14 04:51 UTC, cyberbear181 commented
<img width="1416" alt="image" src="https://user-images.githubusercontent.com/120086676/212454774-1979493e-8256-4cac-851d-ad4417c4301a.png">

2023-01-16 03:35 UTC, tanbowensg commented
挺好的，不过isSSR在runtime和editor里面都写一遍就重复了。应该把他放到 shared 目录中。然后runtime和editor各自从@sunmao/shared 中去 import 进来。

2023-01-16 03:36 UTC, tanbowensg requested changes
应该把 isSSR 移动到 shared 目录中。

2023-01-16 05:42 UTC, tanbowensg commented
另外不要使用绝对路径，使用相对路径，否则 CI 会挂。不过改成@sunmao/shared应该就不会有引用路径问题了。

2023-01-19 08:08 UTC, closed without merging