feat(Editor): add events history
webzard-io/sunmao-ui pull request #685
Opened 2023-02-01 02:08 UTC by xzdry

Listening for all events and displaying logs
![events](https://user-images.githubusercontent.com/96771399/215927451-b42a9dac-25cf-4b53-ae5d-be2d2e8f2440.gif)

2023-02-03 03:04 UTC, tanbowensg requested changes
I think event parameters should be rendered too. Considering parameters are too long to display in table cell, we can display part of parameter and use tooltip to show full parameters.

2023-02-03 03:04 UTC, tanbowensg commented on packages/runtime/src/services/apiService.ts
> +      triggerId?: string;
`triggerId` should be required because every event handler must have a trigger.

2023-02-03 03:04 UTC, tanbowensg commented on packages/editor/src/components/WarningArea/type.ts
> +  triggered: string;
Maybe `triggered` should also be called `triggerId`?

2023-02-03 03:04 UTC, tanbowensg commented on packages/editor/src/components/WarningArea/type.ts
> +  triggerId?: string;
`triggerId` should be required.

2023-02-06 02:06 UTC, xzdry commented
> I think event parameters should be rendered too. Considering parameters are too long to display in table cell, we can display part of parameter and use tooltip to show full parameters.

Completed
<img width="728" alt="image" src="https://user-images.githubusercontent.com/96771399/216865850-d36a8ee9-4f92-4149-996e-8927f184befa.png">

2023-02-06 02:07 UTC, xzdry commented on packages/editor/src/components/WarningArea/type.ts
> +  triggered: string;
done

2023-02-06 02:07 UTC, xzdry commented on packages/editor/src/components/WarningArea/type.ts
> +  triggerId?: string;
done

2023-03-20 07:52 UTC, tanbowensg commented
CI failed

2023-03-20 08:01 UTC, xzdry commented
> CI failed



> CI failed

fixed

2023-03-20 08:19 UTC, tanbowensg approved these changes

2023-03-20 08:19 UTC, merged